name: Remote Deploy from React

on:
  repository_dispatch:
    types: [manual-deploy]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # 1. 쓰기 권한 허용 (에러 128 해결)
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # 2. Node.js 버전을 24로 상향
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_GITHUB_TOKEN: ${{ secrets.VITE_GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist